### PR TITLE
Ensure updates propagate to related entries

### PR DESCRIPTION
**Pull request by aaronbushnell**

### CODE REVIEW

**Comment by janhenckens** [comment]
Good catch! @aaronbushnell should I merge this into the Craft 3 branch as well or are you good there?

**Comment by aaronbushnell** [comment]
> Good catch! @aaronbushnell should I merge this into the Craft 3 branch as well or are you good there?

Ah shoot, forgot to do that! Mind adding it to the Craft 3 version on your side?

**Comment by janhenckens** [comment]
Yes, I'll merge & release when I get home this evening 👍

**Comment by janhenckens** [comment]
Release as 2.8.0-beta.2!

**Pull request merged**
