### PR TITLE
Move element event functions into jobs for significant performance boosts

### PR DESCRIPTION
**Pull request by aaronbushnell**
This definitely needs testing to verify it's not causing a regression for users, but I think this combines the performance improvements noted in studioespresso/craft-scout#171 and [the suggestion to move the event handlers back to queued jobs](https://github.com/studioespresso/craft-scout/discussions/247).

First off, I'm using the suggested revision from @EpocSquardron to add the `$element->shouldBeSearchable()` condition before triggering the events. This will exclude things like Neo blocks from being processed when the save and deletion events occur.

Secondly, I moved the functions—notably the `$element->getRelatedElements()` one which is very taxing when you have numerous relationships—to queued jobs so they don't hold up save and deletion events.

I couldn't quite determine how you all have your Craft 3 and Craft 4 branches set up, but I hope this is at least a start to adding some nice performance boosts without having to resort to setting valuable options like `indexRelations` to `false`.

### CODE REVIEW

**Comment by janhenckens** [comment]
Hey @aaronbushnell, 1 issue this would introduce this that Scout has a `queue` setting right now, which is checked in [`SearchableBehavior`](https://github.com/studioespresso/craft-scout/blob/master/src/behaviors/SearchableBehavior.php#L83).

This PR would make a queue job outright, even for people who have that setting disabled. And extra check for that setting would fix that, but I don't really that we'd be fire 2 jobs for each save. 

(that's for the searchable action, moving the removable of old revisions out to the queue if the user has the setting enabled is definitely the way to go)

Happy to hear your thoughts!

**Comment by aaronbushnell** [comment]
Ooo, that's a good catch, @janhenckens! Personally, I think—

1. The queue should always be used
2. The setting to toggle it on or off should be deprecated

Unless there's some reason people are turning this off that I'm unaware of I think this process shouldn't hold up things like:

- Updating an entry
- Deleting an entry
- Deleting a revision
- Saving a draft
- Publishing a draft

Not only would that speed up the existing publishing workflow (since those element events currently aren't processed in a queue), but it also reduces the config and different paths you are having to account for across the plugin.

I'm open to thoughts, but I don't think this should block publishing workflows since it can be easily deferred to a job.

**Comment by janhenckens** [comment]
> * The queue should always be used
> * The setting to toggle it on or off should be deprecated

Agreed, don't think we've run Scout outside of the queue anywhere ever.

We can deprecate the setting and release a fix with your PR, and then remove the option on the next major version. Would you be up for testing a beta release?

**Comment by aaronbushnell** [comment]
Absolutely! Thanks so much and let me know how I can help, @janhenckens!

**Comment by janhenckens** [comment]
Going to merge this in a separate branch to see if I can make the current `queue` option work with this. I'll keep this open to keep you up to date!

**Comment by janhenckens** [comment]
@aaronbushnell Just pushed 2.8.0-beta.1 which should work for Craft 3. Can you give it a spin?

**Comment by aaronbushnell** [comment]
Wow, so much better @janhenckens! Tried a handful of saves and it's much speedier!

**Comment by janhenckens** [comment]
Happy to hear that @aaronbushnell. If you're willing to run this in production we can do that for a couple of weeks while I look for a way to negate the double-queue-job issue.

**Comment by aaronbushnell** [comment]
Hey @janhenckens — I'll check with our internal team to verify if that's okay for us to do and get client approval. Will follow up there!

FWIW here's some benchmarks on this update for reference:

## Saving an entry change w/ many relationships (before 2.8.0, local environment)
26,512 ms
25,346 ms
21,826 ms

## Saving an entry change w/ many relationships (after 2.8.0, local environment)
2,822 ms
2,252 ms
2,235 ms

**Pull request merged**
